### ISSUE TITLE
 Linux卡住了

### ISSUE THREAD

**Issue by zhiyongye** [ncuopen/ncuopen.github.io#1]
Linux突然就卡住了，不能输命令，按键盘也没反应（键盘没坏），Ctrl+C和Ctrl+d都没用，怎么回事

**Comment by guodongxiaren** [comment]
是不是你按了ctrl+s挂起了。好像ctrl+q可以取消挂起。不知道你是不是这个原因

**Comment by zhiyongye** [comment]
我试了一下，好像是这个原因，谢谢了
