### ISSUE TITLE
大家好，问几个问题

### ISSUE THREAD

**Issue by CK-AK** [ncuopen/ncuopen.github.io#7]
1，大家多长时间来看一次
2，我的centos 安装sdcc一直失败
这些项目显示的是no
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking machine/endian.h usability... no
checking machine/endian.h presence... no
checking for machine/endian.h... no
checking sys/isa_defs.h usability... no
checking sys/isa_defs.h presence... no
checking for sys/isa_defs.h... no
checking how to run the C++ preprocessor... g++ -E
checking stx/btree_set.h usability... no
checking stx/btree_set.h presence... no
checking for stx/btree_set.h... no
configure: WARNING: STX library missing, using STL instead.
checking stx/btree_map.h usability... no
checking stx/btree_map.h presence... no
checking for stx/btree_map.h... no
configure: WARNING: STX library missing, using STL instead.
checking boost/graph/adjacency_list.hpp usability... no
checking boost/graph/adjacency_list.hpp presence... no
checking for boost/graph/adjacency_list.hpp... no
configure: error: boost library not found (boost/graph/adjacency_list.hpp).

能告诉我该怎么办嘛？

**Comment by guodongxiaren** [comment]
很明显是缺少boost库。有问题去群里问。这里回复很慢。
